services:
    mariadb-catalogs:
        build:
            context: .
            dockerfile: Dockerfile
        image: mariadb/catalogs:0.3
        restart: unless-stopped
        ports:
            - '${DB_PORT:-3306}:3306'
        volumes:
            - 'mariadb:/datadir'
volumes:
    mariadb:
        driver: local
